# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tables.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import datetime
from PyQt5.QtGui import *
from PyQt5.QtWidgets import (QWidget, QTableWidget, QHBoxLayout, QApplication, QTableWidgetItem)
from PyQt5.QtGui import QBrush, QColor
from PyQt5 import QtCore
class TelemetryWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1245, 564)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(10, 70, 1221, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(12)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(19)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(29)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        
        self.tableWidget_2 = QtWidgets.QTableWidget(Form)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 340, 1221, 201))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(13)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(12, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(88)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        d1 = datetime.datetime(2022,1,30,12,0,0)
        d2 = datetime.datetime(2022,1,30,12,0,1)
        d3 = datetime.datetime(2022,1,30,12,0,2)
        d4 = datetime.datetime(2022,1,30,12,0,3)
        d5 = datetime.datetime(2022,1,30,12,0,4)
        d6 = datetime.datetime(2022,1,30,12,0,5)
        d7 = datetime.datetime(2022,1,30,12,0,6)
        d8 = datetime.datetime(2022,1,30,12,0,7)
        ##MODE ,TP_RELEASED,ALT,_TEMP,VOLT,GPS_TIME,LAT,LONG,ALT,SAT,SW_STATE,CMD_ECHO
        containerT=[["F","R",250,18.2,4,d1,39.8849, 32.7778,3000,15,1,"CXON"]
          ,["F","R",245,18.3,5,d2,39.8849, 32.7778,2995,15,1,"CXON"]
          ,["F","R",240,18.4,4.5,d3,39.8849, 32.7778,2990,15,1,"CXON"]
          ,["F","R",235,18.4,5.5,d4,39.8849, 32.7778,2985,15,1,"CXON"]
          ,["F","R",230,18.5,4.7,d5,39.8849, 32.7778,2980,15,1,"CXON"]
          ,["F","R",225,18.4,5.2,d6,39.8849, 32.7778,2975,15,1,"CXON"]
          ,["F","R",220,18.6,5,d7,39.8849, 32.7778,2970,15,1,"CXON"]
          ,["F","R",215,18.6,4.8,d8,39.8849, 32.7778,2965,15,1,"CXON"]]
        payloadT  =[[230,18.2,15,29,41,0.1,0.1,0.1,0.1,0.1,0.1,0.1,"RELEASED"],
                    [225,18.1,16,30,43,0.2,0.1,0.2,0.1,0.1,0.1,0.2,"RELEASED"],
                    [220,18.3,17,32,42,0.1,0 ,0.1,0.1,0.1,0.1,0.1,"RELEASED"],
                    [215,18.3,16,28,39,0.1,0.1,0.1,0.1,0.1,0.1,0.2,"RELEASED"],
                    [210,18.3,17,29,38,0.1,0.1,0,0.1,0.1,0.1,0.1,"RELEASED"],
                    [205,18.3,16,30,40,0.1,0.1,0.1,0.1,0.1,0.1,0.1,"RELEASED"],
                    [200,18.4,17,32,41,0,0,0.1,0.1,0.1,0.1,0,"RELEASED"],
                    [195,18.4,16,33,42,0.1,0 ,0,0.1,0.1,0.1,0.1,"RELEASED"],]
        k=0
        z=0
        for i in containerT:
            z=0
            numRows = self.tableWidget.rowCount()
            self.tableWidget.insertRow(numRows)  
            for j in i:
                self.tableWidget.setItem(k,z,QTableWidgetItem(str(j)))
                z+=1
            k+=1
        k=0
        for i in payloadT:
            z=0
            numRows = self.tableWidget_2.rowCount()
            self.tableWidget_2.insertRow(numRows)  
            for j in i:
                self.tableWidget_2.setItem(k,z,QTableWidgetItem(str(j)))
                z+=1
            k+=1
        
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Telemetry"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "MODE"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "TP_RELEASED"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "ALT"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "TEMP"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "VOLTAGE"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "GPS_TIME"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "GPS_LAT"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "GPS_LONG"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "GPS_ALT"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Form", "GPS_SAT"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("Form", "SW_STATE"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("Form", "CMD_ECHO"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "TP_ALT"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "TP_TEMP"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "GYRO_R"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "GYRO_P"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Form", "GYRO_Y"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Form", "ACCEL_R"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("Form", "ACCEL_P"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("Form", "ACCEL_Y"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("Form", "MAG_R"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("Form", "MAG_P"))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(_translate("Form", "MAG_Y"))
        item = self.tableWidget_2.horizontalHeaderItem(11)
        item.setText(_translate("Form", "POINTING_ERROR"))
        item = self.tableWidget_2.horizontalHeaderItem(12)
        item.setText(_translate("Form", "TP_SW_STATE"))
        
    def getContainerTable(self):
        return self.tableWidget
    def getPayloadTable(self):
        return self.tableWidget_2
    

